name: Eatable
author: Rayzs_YT
description: Make any item eatable

version: 0.0.1
api-version: 1.21

main: de.rayzs.eatable.plugin.EatablePlugin

commands:

  eatable:
    aliases: [food]
    description: Turn an item into consumable food